### ISSUE TITLE
relaunch skyportal errors in astropy

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1777]
After merging the latest from skyportal master I get errors.  I think they are related to baselayer and packages.

One error is

> 2021-03-12 14:38:23,159 INFO spawned: 'app_01' with pid 243040                config.yaml.defaults
> 
> AttributeError: module 'astropy.cosmology' has no attribute 'Planck18_arXiv_v2'
>                 config.yaml

**Comment by AlexGKim** [comment]
When upgrading I get a message like `config.yaml app.routes differs from config.yaml.defaults`.  Is there a way around recopying config.yaml.defaults to config.yaml and finding and editing the few places that need a change?

**Comment by stefanv** [comment]
@dmitryduev What was the purpose of this check again?  Users should be able to add routes to their servers if they want to.

**Comment by AlexGKim** [comment]
Despite the error above I confirm that my astropy.cosmology does have the attribute.

> >>> print(astropy.cosmology.Planck18_arXiv_v2)
> FlatLambdaCDM(name="Planck18_arXiv_v2", H0=67.7 km / (Mpc s), Om0=0.31, Tcmb0=2.725 K, Neff=3.05, m_nu=[0.   0.   0.06] eV, Ob0=0.049)

**Comment by stefanv** [comment]
Can you check that this is the same version that runs in the SkyPortal container / environment?  I've never seen that error before.

**Comment by AlexGKim** [comment]
Are you referring to astropy?

>>> astropy.__version__
'4.0.1.post1'

**Comment by AlexGKim** [comment]
There was a new package I had to install because of baselayer `deepxxx`, (I don't remember the name).  This overwrote existing package.

**Comment by AlexGKim** [comment]
The container/environment is running astropy 3.2.3.

**Comment by stefanv** [comment]
You need 4.2, according to the requirements.txt file

**Comment by AlexGKim** [comment]
How do I do that?

**Comment by AlexGKim** [comment]
Thanks I have upgraded to 4.2, there does seem to be a package `attr` missing still that I don't see in the requirements.

```
 File "/home/akim/miniconda3/envs/skyportal_env/lib/python3.8/site-packages/jsonschema/exceptions.py", line 9, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

**Comment by AlexGKim** [comment]
I do have the attrs package installed.
```
(skyportal_env) [akim@desi2 skyportal]$ pip list
Package                        Version            
------------------------------ -------------------
alabaster                      0.7.12             
alembic                        1.5.5              
apispec                        4.0.0              
APLpy                          2.0.3              
arrow                          0.15.4             
astroplan                      0.8                
astropy                        4.2                
astropy-healpix                0.5                
astroquery                     0.4.1              
attrs                          20.3.0  
```

**Comment by stefanv** [comment]
That looks like an issue with the jsonschema library. Please check that you have the correct version of that installed too.

We check these in CI, and when doing `make run`, so I'm a bit surprised that you're having issues.

**Comment by AlexGKim** [comment]
I am running the version of jsonschema in requirements.txt.

jsonschema                3.2.0

**Comment by stefanv** [comment]
Odd, please can you provide the full traceback?

**Comment by AlexGKim** [comment]
> config.yaml app.routes matches that of config.yaml.defaults
>   Config files: baselayer/config.yaml.defaults
>                 config.yaml.defaults
>                 config.yaml
> Created TAP+ (v1.2.1) - Connection:
>         Host: gea.esac.esa.int
>         Use HTTPS: True
>         Port: 443
>         SSL Port: 443
> Created TAP+ (v1.2.1) - Connection:
>         Host: geadata.esac.esa.int
>         Use HTTPS: True
>         Port: 443
>         SSL Port: 443
> ^[[37;1m[16:07:52 cosmology] using Planck18_arXiv_v2 for cosmological calculations^[[0m
> ^[[37;1m[16:07:52 cosmology] FlatLambdaCDM(name="Planck18_arXiv_v2", H0=67.7 km / (Mpc s), Om0=0.31, Tcmb0=2.725 K, Neff=3.05, m_nu=[0.   0.   0.06] eV, Ob0=0.049)^[[0m
> /home/akim/miniconda3/envs/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py:1823: SAWarning: Property Obj.candidates on mapped class Obj->objs being replaced with new property Obj.candidates; the old property will be discarded
>   util.warn(
> /home/akim/miniconda3/envs/skyportal_env/lib/python3.8/site-packages/sqlalchemy/ext/declarative/clsregistry.py:125: SAWarning: This declarative base already contains a class with the same class name and module name as baselayer.app.models.SpectrumUser, and will be replaced in the string-lookup table.
>   util.warn(
> Traceback (most recent call last):
>   File "baselayer/services/app/app.py", line 36, in <module>
>     app_factory = getattr(importlib.import_module(module), app_factory)
>   File "/home/akim/miniconda3/envs/skyportal_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/akim/skyportal/skyportal/app_server.py", line 8, in <module>
>     from skyportal.handlers.api import (
>   File "/home/akim/skyportal/skyportal/handlers/api/__init__.py", line 9, in <module>
>     from .followup_request import FollowupRequestHandler, AssignmentHandler
>   File "/home/akim/skyportal/skyportal/handlers/api/followup_request.py", line 1, in <module>
>     import jsonschema
>   File "/home/akim/miniconda3/envs/skyportal_env/lib/python3.8/site-packages/jsonschema/__init__.py", line 11, in <module>
>     from jsonschema.exceptions import (
>   File "/home/akim/miniconda3/envs/skyportal_env/lib/python3.8/site-packages/jsonschema/exceptions.py", line 9, in <module>
>     import attr
> ModuleNotFoundError: No module named 'attr'

**Comment by AlexGKim** [comment]
I uninstalled attrs and jsonschema and reinstalled.  I no longer get this error.

**Comment by AlexGKim** [comment]
SkyPortal is back up running.

**Comment by stefanv** [comment]
Glad to hear it, Alex!
