### ISSUE TITLE
d3-geo-zoom version 1.5.5 breaks the GCN events page

### ISSUE THREAD

**Issue by antoine-le-calloch** [skyportal/skyportal#5859]
## Description:
The GCN events page is no longer working due to the following error:
```
SES_UNCAUGHT_EXCEPTION: Error: Cannot find module 'versor/src/index'
```
This issue appeared after upgrading `d3-geo-zoom` from 1.4.4 to 1.5.5.

It seems that there is currently no better solution than downgrading one of the two packages (versor or d3-geo-zoom).

## Temporary workaround

d3-geo-zoom has been downgraded back to 1.4.4 to fix the issue.

## Next steps

A PR has been opened on the package’s GitHub with a proposed fix: https://github.com/vasturiano/d3-geo-zoom/pull/19

**Comment by mcoughlin** [comment]
Removed this package.
